#[derive(Clone, serde::Deserialize, serde::Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ClickerSettings {
    pub version: u32,
    pub click_speed: f64,
    pub click_interval: String,
    pub mouse_button: String,
    pub mode: String,
    pub hotkey: String,
    pub duty_cycle_enabled: bool,
    pub duty_cycle: f64,
    pub speed_variation_enabled: bool,
    pub speed_variation: f64,
    pub double_click_enabled: bool,
    pub double_click_delay: u32,
    pub click_limit_enabled: bool,
    pub click_limit: i32,
    pub time_limit_enabled: bool,
    pub time_limit: f64,
    pub time_limit_unit: String,
    pub corner_stop_enabled: bool,
    #[serde(rename = "cornerStopTL")]
    pub corner_stop_tl: i32,
    #[serde(rename = "cornerStopTR")]
    pub corner_stop_tr: i32,
    #[serde(rename = "cornerStopBL")]
    pub corner_stop_bl: i32,
    #[serde(rename = "cornerStopBR")]
    pub corner_stop_br: i32,
    pub edge_stop_enabled: bool,
    pub edge_stop_top: i32,
    pub edge_stop_right: i32,
    pub edge_stop_bottom: i32,
    pub edge_stop_left: i32,
    pub position_enabled: bool,
    pub position_x: i32,
    pub position_y: i32,
    pub disable_screenshots: bool,
    pub advanced_settings_enabled: bool,
    pub explanation_mode: String,
    pub last_panel: String,
    pub show_stop_reason: bool,
    pub show_stop_overlay: bool,
    pub strict_hotkey_modifiers: bool,
}

impl Default for ClickerSettings {
    fn default() -> Self {
        Self {
            version: 3,
            click_speed: 25.0,
            click_interval: "s".to_string(),
            mouse_button: "Left".to_string(),
            mode: "Toggle".to_string(),
            hotkey: "ctrl+y".to_string(),
            duty_cycle_enabled: true,
            duty_cycle: 45.0,
            speed_variation_enabled: true,
            speed_variation: 35.0,
            double_click_enabled: false,
            double_click_delay: 40,
            click_limit_enabled: false,
            click_limit: 1000,
            time_limit_enabled: false,
            time_limit: 60.0,
            time_limit_unit: "s".to_string(),
            corner_stop_enabled: true,
            corner_stop_tl: 50,
            corner_stop_tr: 50,
            corner_stop_bl: 50,
            corner_stop_br: 50,
            edge_stop_enabled: true,
            edge_stop_top: 40,
            edge_stop_right: 40,
            edge_stop_bottom: 40,
            edge_stop_left: 40,
            position_enabled: false,
            position_x: 0,
            position_y: 0,
            disable_screenshots: false,
            advanced_settings_enabled: true,
            explanation_mode: "text".to_string(),
            last_panel: "simple".to_string(),
            show_stop_reason: true,
            show_stop_overlay: true,
            strict_hotkey_modifiers: false,
        }
    }
}
